app = "codeshali"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/data/codeshali.db"

[mounts]
  source      = "job_data"
  destination = "/data"

[http_service]
  internal_port       = 5000
  force_https         = false
  auto_stop_machines  = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "256mb"
